In [2]:
#Consider the below code to answer further questions:

import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of the list_ and array_list variables.
The list_ variable is a Python list of strings, whereas array_list is a NumPy array of strings. Although they both contain the same string values, they have different data types because they are different types of objects.

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
for i in list_:
    print(f"Value: {i}, Datatype: {type(i)}")

Value: 1, Datatype: <class 'str'>
Value: 2, Datatype: <class 'str'>
Value: 3, Datatype: <class 'str'>
Value: 4, Datatype: <class 'str'>
Value: 5, Datatype: <class 'str'>


In [8]:
for i in array_list:
    print(f"Value: {i}, Datatype: {type(i)}")

Value: 1, Datatype: <class 'numpy.str_'>
Value: 2, Datatype: <class 'numpy.str_'>
Value: 3, Datatype: <class 'numpy.str_'>
Value: 4, Datatype: <class 'numpy.str_'>
Value: 5, Datatype: <class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
type(array_list)

numpy.ndarray

Yes There will be difference in datatypes of elements present in both lists.
List elements will have data type string and array_list will have datatype numpy integer

In [12]:
for i in list_:
    print(f"Value: {i}, Datatype: {type(i)}")

Value: 1, Datatype: <class 'str'>
Value: 2, Datatype: <class 'str'>
Value: 3, Datatype: <class 'str'>
Value: 4, Datatype: <class 'str'>
Value: 5, Datatype: <class 'str'>


In [11]:
for i in array_list:
    print(f"Value: {i}, Datatype: {type(i)}")

Value: 1, Datatype: <class 'numpy.int32'>
Value: 2, Datatype: <class 'numpy.int32'>
Value: 3, Datatype: <class 'numpy.int32'>
Value: 4, Datatype: <class 'numpy.int32'>
Value: 5, Datatype: <class 'numpy.int32'>


### Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
num_list

[[1, 2, 3], [4, 5, 6]]

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [16]:
num_array.shape

(2, 3)

In [17]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
arr1  = np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr1.shape

(3, 3)

In [25]:
arr1.size

9

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])